[project]
name = "treqz"
version = "1.0.0"
description = ""
authors = [
    {name = "Till Uhlig"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "lxml (>=5.3.2,<6.0.0)",
    "pytz (>=2025.2,<2026.0)"
]

[tool.poetry]
packages = [ {include="TReqz"}]
exclude = [
    "TReqZ/tests/**",
    "TReqZ/examples/**"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
